### ISSUE TITLE
Any ideas of how we could plot linear DNA and overlay sequence alignments?

### ISSUE THREAD

**Issue by ppreshant** [BradyAJohnston/plasmapR#3]
Hi Brady, just ran into your project thinking of overlaying alignments onto an annotated DNA image. Thanks for your excellent work on this package. My use case is a little niche, and I was hoping to build on your package or see if you have any suggestions for my task. 

I'm trying to get an intuitive sense of my > 50,000 reads amplicon sequencing dataset + the effect of the processing pipeline. I would like to make a series of mappings / pairwise alignments and represent it as a bar chart with a colour coded line for each unique read by aligned regions.. I don't know of any existing tool that summarizes alignments so succinctly.

It would be nice if we could plot linear DNA with your package (maybe as simple as removing the polar co-ordinates!?). Here's a python one I found if you have any thoughts on this - [DNA Features Viewer](https://edinburgh-genome-foundry.github.io/DnaFeaturesViewer/)

**Comment by BradyAJohnston** [comment]
Could maybe have a look at [gggenes](https://wilkox.org/gggenes/) which might be more well suited for the task. 

If you give me more of an example of what the data looks like I could give a more informed idea :)

**Comment by ppreshant** [comment]
Thank you for the reply! gggenes looks interesting. I'll play around with it and get back with anything I find relevant. 

I mean something like the graphic summary that BLAST outputs in the online server. With R or Python, I am hoping to overlay it with the annotations from a genbank file that tracks the same sequence numbering as the alignment's query 
![image](https://user-images.githubusercontent.com/14856479/202589166-69c82d1f-62a4-412f-a9dc-46a6dc7757b4.png)

**Comment by BradyAJohnston** [comment]
Annotations like that from BLAST would be easy enough to pull off inside of ggplot, just depends on the initial data you are dealing with

**Comment by ppreshant** [comment]
That makes sense. Thanks for your feedback. 

I'll close this issue and reopen it when I have something to share on this idea 🙂
